// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/customers/{id}/verify-otp": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Verify OTP for customer account activation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Verify customer OTP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "OTP verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Response"
                        }
                    }
                }
            }
        },
        "/customers": {
            "get": {
                "description": "Get a list of customers with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "List customers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new customer. Only accessible by gym owners.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Register a new customer",
                "parameters": [
                    {
                        "description": "Customer information",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.CreateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden - Not a gym owner",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/customers/by-goal/{goal}": {
            "get": {
                "description": "Get a list of customers with a specific fitness goal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "List customers by fitness goal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fitness goal",
                        "name": "goal",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/customers/{id}": {
            "get": {
                "description": "Get customer details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Get a customer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update customer details. Only accessible by authenticated users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Update a customer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Customer information",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.UpdateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft delete a customer. Only accessible by authenticated users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "Delete a customer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gym-owners/customers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all customers under the gym owner's management",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "List gym customers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new customer under the gym owner's management",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Create customer for gym",
                "parameters": [
                    {
                        "description": "Customer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.CreateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gym-owners/login": {
            "post": {
                "description": "Authenticate a gym owner and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Login gym owner",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gym-owners/register": {
            "post": {
                "description": "Register a new gym owner with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Register a new gym owner",
                "parameters": [
                    {
                        "description": "Gym owner registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.CreateGymOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.GymOwner"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gym-owners/trainers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all trainers under the gym owner's management",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "List gym trainers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Trainer"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new trainer under the gym owner's management",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Create trainer for gym",
                "parameters": [
                    {
                        "description": "Trainer details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.CreateTrainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Trainer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gym-owners/verify-otp": {
            "post": {
                "description": "Verify OTP for gym owner account activation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "OTP verification details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/gym-owners/{id}": {
            "get": {
                "description": "Get gym owner details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Get gym owner profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Gym Owner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.GymOwner"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update gym owner information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Update gym owner profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Gym Owner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.UpdateGymOwnerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.GymOwner"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a gym owner. This endpoint is public and does not require authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gym-owners"
                ],
                "summary": "Delete a gym owner",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Gym Owner ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/otp/send": {
            "post": {
                "description": "Send an OTP to the specified target (email/phone)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "otp"
                ],
                "summary": "Send OTP",
                "parameters": [
                    {
                        "description": "OTP Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.SendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/otp/verify": {
            "post": {
                "description": "Verify an OTP for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "otp"
                ],
                "summary": "Verify OTP",
                "parameters": [
                    {
                        "description": "Verify OTP Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.VerifyOTPResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/trainers": {
            "get": {
                "description": "Get a paginated list of all trainers. This endpoint is publicly accessible.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainers"
                ],
                "summary": "List trainers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.TrainerListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new trainer. Only accessible by gym owners.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainers"
                ],
                "summary": "Create a new trainer",
                "parameters": [
                    {
                        "description": "Trainer information",
                        "name": "trainer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.CreateTrainerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Trainer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden - Not a gym owner",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/trainers/verify-otp": {
            "post": {
                "description": "Verify OTP for trainer activation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainers"
                ],
                "summary": "Verify trainer OTP",
                "parameters": [
                    {
                        "description": "OTP verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/trainers/{id}": {
            "get": {
                "description": "Get detailed information about a specific trainer. This endpoint is publicly accessible.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainers"
                ],
                "summary": "Get a trainer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trainer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Trainer"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update trainer information. Only accessible by authenticated users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainers"
                ],
                "summary": "Update a trainer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trainer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trainer information",
                        "name": "trainer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.UpdateTrainerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Trainer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft delete a trainer. Only accessible by authenticated users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trainers"
                ],
                "summary": "Delete a trainer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trainer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_yourname_fitness-platform_internal_models.CreateCustomerRequest": {
            "description": "Request to create a new customer",
            "type": "object",
            "required": [
                "age",
                "email",
                "full_name",
                "gender",
                "height",
                "phone",
                "weight"
            ],
            "properties": {
                "age": {
                    "description": "@Description Age of the customer\n@example 25",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 18
                },
                "email": {
                    "description": "@Description Email address of the customer\n@example john.doe@example.com",
                    "type": "string"
                },
                "fitness_goals": {
                    "description": "@Description Fitness goals of the customer\n@example [\"Weight Loss\", \"Muscle Gain\"]",
                    "type": "string"
                },
                "full_name": {
                    "description": "@Description Full name of the customer\n@example John Doe",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "gender": {
                    "description": "@Description Gender of the customer\n@example male",
                    "enum": [
                        "male",
                        "female",
                        "other"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Gender"
                        }
                    ]
                },
                "health_conditions": {
                    "description": "@Description Health conditions of the customer\n@example [\"Asthma\", \"Back Pain\"]",
                    "type": "string"
                },
                "height": {
                    "description": "@Description Height of the customer in centimeters\n@example 175",
                    "type": "number",
                    "maximum": 250,
                    "minimum": 100
                },
                "phone": {
                    "description": "@Description Phone number of the customer\n@example +1234567890",
                    "type": "string"
                },
                "profile_url": {
                    "description": "@Description Profile URL of the customer\n@example https://example.com/profile.jpg",
                    "type": "string"
                },
                "weight": {
                    "description": "@Description Weight of the customer in kilograms\n@example 70",
                    "type": "number",
                    "maximum": 300,
                    "minimum": 30
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.CreateGymOwnerRequest": {
            "description": "Request to create a new gym owner",
            "type": "object",
            "required": [
                "email",
                "full_name",
                "gym_name",
                "gym_registration_number",
                "password",
                "phone"
            ],
            "properties": {
                "email": {
                    "description": "@Description Email address of the gym owner\n@example john.doe@example.com",
                    "type": "string"
                },
                "full_name": {
                    "description": "@Description Full name of the gym owner\n@example John Doe",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "gym_name": {
                    "description": "@Description Name of the gym\n@example Fitness First",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "gym_registration_number": {
                    "description": "@Description Registration number of the gym\n@example GYM123456",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 5
                },
                "password": {
                    "description": "@Description Password for the gym owner account\n@example securePassword123",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8
                },
                "phone": {
                    "description": "@Description Phone number of the gym owner\n@example +1234567890",
                    "type": "string"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.CreateTrainerRequest": {
            "description": "Request body for creating a new trainer",
            "type": "object",
            "required": [
                "bio",
                "email",
                "experience",
                "first_name",
                "last_name",
                "password",
                "phone",
                "specialization"
            ],
            "properties": {
                "bio": {
                    "description": "@Description Detailed trainer biography\n@Example Certified personal trainer with expertise in strength training and rehabilitation.",
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 10
                },
                "email": {
                    "description": "@Description Email address (must be unique)\n@Example john.trainer@gymapp.com",
                    "type": "string"
                },
                "experience": {
                    "description": "@Description Years of experience\n@Example 5",
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 0
                },
                "first_name": {
                    "description": "@Description Trainer's first name\n@Example John",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "last_name": {
                    "description": "@Description Trainer's last name\n@Example Smith",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "password": {
                    "description": "@Description Password for the account\n@Example SecurePass123!",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8
                },
                "phone": {
                    "description": "@Description Phone number (must be unique)\n@Example +1-555-123-4567",
                    "type": "string"
                },
                "specialization": {
                    "description": "@Description Area of expertise\n@Example Strength Training",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.Customer": {
            "description": "Customer information",
            "type": "object",
            "properties": {
                "age": {
                    "description": "@Description Age of the customer\n@example 25",
                    "type": "integer"
                },
                "created_at": {
                    "description": "@Description Creation timestamp",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "@Description Soft delete timestamp",
                    "allOf": [
                        {
                            "$ref": "#/definitions/gorm.DeletedAt"
                        }
                    ]
                },
                "email": {
                    "description": "@Description Email address of the customer\n@example john.doe@example.com",
                    "type": "string"
                },
                "fitness_goals": {
                    "description": "@Description Fitness goals of the customer\n@example [\"Weight Loss\", \"Muscle Gain\"]",
                    "type": "string"
                },
                "full_name": {
                    "description": "@Description Full name of the customer\n@example John Doe",
                    "type": "string"
                },
                "gender": {
                    "description": "@Description Gender of the customer\n@example male",
                    "type": "string"
                },
                "gym_owner_id": {
                    "description": "@Description Gym owner ID\n@example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "health_conditions": {
                    "description": "@Description Health conditions of the customer\n@example [\"Asthma\", \"Back Pain\"]",
                    "type": "string"
                },
                "height": {
                    "description": "@Description Height of the customer in centimeters\n@example 175",
                    "type": "number"
                },
                "id": {
                    "description": "@Description Unique identifier for the customer\n@example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "is_active": {
                    "description": "@Description Whether the customer is active\n@example false",
                    "type": "boolean"
                },
                "phone": {
                    "description": "@Description Phone number of the customer\n@example +1234567890",
                    "type": "string"
                },
                "profile_url": {
                    "description": "@Description Profile URL of the customer\n@example https://example.com/profile.jpg",
                    "type": "string"
                },
                "role": {
                    "description": "@Description Role of the customer\n@example customer",
                    "type": "string"
                },
                "updated_at": {
                    "description": "@Description Last update timestamp",
                    "type": "string"
                },
                "weight": {
                    "description": "@Description Weight of the customer in kilograms\n@example 70",
                    "type": "number"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.Gender": {
            "type": "string",
            "enum": [
                "male",
                "female",
                "other",
                "unknown"
            ],
            "x-enum-varnames": [
                "GenderMale",
                "GenderFemale",
                "GenderOther",
                "GenderUnknown"
            ]
        },
        "github_com_yourname_fitness-platform_internal_models.GymOwner": {
            "description": "Gym owner information",
            "type": "object",
            "required": [
                "email",
                "full_name",
                "gym_name",
                "gym_registration_number",
                "id",
                "phone"
            ],
            "properties": {
                "created_at": {
                    "description": "@Description Creation timestamp",
                    "type": "string"
                },
                "email": {
                    "description": "@Description Email address of the gym owner\n@example john.doe@example.com",
                    "type": "string"
                },
                "full_name": {
                    "description": "@Description Full name of the gym owner\n@example John Doe",
                    "type": "string"
                },
                "gym_name": {
                    "description": "@Description Name of the gym\n@example Fitness First",
                    "type": "string"
                },
                "gym_registration_number": {
                    "description": "@Description Registration number of the gym\n@example GYM123456",
                    "type": "string"
                },
                "id": {
                    "description": "@Description Unique identifier for the gym owner\n@example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "is_active": {
                    "description": "@Description Whether the gym owner is active\n@example false",
                    "type": "boolean"
                },
                "phone": {
                    "description": "@Description Phone number of the gym owner\n@example +1234567890",
                    "type": "string"
                },
                "updated_at": {
                    "description": "@Description Last update timestamp",
                    "type": "string"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.LoginRequest": {
            "description": "Login request details",
            "type": "object",
            "required": [
                "password",
                "user_type",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "@Description Password\n@example securePassword123",
                    "type": "string",
                    "minLength": 8
                },
                "user_type": {
                    "description": "@Description Type of user (gym_owner, trainer, customer)\n@example trainer",
                    "enum": [
                        "gym_owner",
                        "trainer",
                        "customer"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.UserType"
                        }
                    ]
                },
                "username": {
                    "description": "@Description Email address or phone number\n@example john.doe@example.com",
                    "type": "string"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.OTPTarget": {
            "type": "string",
            "enum": [
                "gym_owner",
                "trainer",
                "customer"
            ],
            "x-enum-varnames": [
                "OTPTargetGymOwner",
                "OTPTargetTrainer",
                "OTPTargetCustomer"
            ]
        },
        "github_com_yourname_fitness-platform_internal_models.OTPType": {
            "type": "string",
            "enum": [
                "email",
                "phone"
            ],
            "x-enum-varnames": [
                "OTPTypeEmail",
                "OTPTypePhone"
            ]
        },
        "github_com_yourname_fitness-platform_internal_models.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.SendOTPRequest": {
            "description": "Request to send OTP",
            "type": "object",
            "required": [
                "target",
                "target_type",
                "type"
            ],
            "properties": {
                "target": {
                    "description": "@Description Target value (email or phone number)\n@example john.doe@example.com",
                    "type": "string"
                },
                "target_type": {
                    "description": "@Description Target user type\n@example customer",
                    "enum": [
                        "gym_owner",
                        "trainer",
                        "customer"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.OTPTarget"
                        }
                    ]
                },
                "type": {
                    "description": "@Description Target type (email or phone)\n@example email",
                    "enum": [
                        "email",
                        "phone"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.OTPType"
                        }
                    ]
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.Trainer": {
            "description": "Trainer information including personal details and profile",
            "type": "object",
            "required": [
                "email",
                "first_name",
                "id",
                "last_name",
                "phone"
            ],
            "properties": {
                "created_at": {
                    "description": "@Description When the trainer was created\n@Example 2024-03-15T14:30:00Z",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "@Description Soft delete timestamp (null if not deleted)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/gorm.DeletedAt"
                        }
                    ]
                },
                "email": {
                    "description": "@Description Email address of the trainer (must be unique)\n@Example john.trainer@gymapp.com",
                    "type": "string"
                },
                "first_name": {
                    "description": "@Description First name of the trainer\n@Example John",
                    "type": "string"
                },
                "gym_owner_id": {
                    "description": "@Description ID of the gym owner this trainer belongs to\n@Example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "description": "@Description Whether the trainer account is active\n@Example false",
                    "type": "boolean"
                },
                "last_name": {
                    "description": "@Description Last name of the trainer\n@Example Smith",
                    "type": "string"
                },
                "phone": {
                    "description": "@Description Phone number of the trainer (must be unique)\n@Example +1-555-123-4567",
                    "type": "string"
                },
                "profile": {
                    "description": "@Description Trainer's detailed profile information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.TrainerProfile"
                        }
                    ]
                },
                "role": {
                    "description": "@Description Role of the user (always 'trainer')\n@Example trainer",
                    "type": "string"
                },
                "updated_at": {
                    "description": "@Description When the trainer was last updated\n@Example 2024-03-15T14:30:00Z",
                    "type": "string"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.TrainerListResponse": {
            "description": "Paginated response containing a list of trainers",
            "type": "object",
            "properties": {
                "limit": {
                    "description": "@Description Number of items per page\n@Example 10",
                    "type": "integer"
                },
                "page": {
                    "description": "@Description Current page number\n@Example 1",
                    "type": "integer"
                },
                "total": {
                    "description": "@Description Total number of trainers matching the query\n@Example 100",
                    "type": "integer"
                },
                "trainers": {
                    "description": "@Description List of trainers",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Trainer"
                    }
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.TrainerProfile": {
            "description": "Detailed profile information for a trainer",
            "type": "object",
            "required": [
                "bio",
                "id",
                "specialization",
                "trainer_id"
            ],
            "properties": {
                "bio": {
                    "description": "@Description Detailed biography of the trainer\n@Example Certified personal trainer with expertise in strength training and rehabilitation.",
                    "type": "string"
                },
                "created_at": {
                    "description": "@Description When the profile was created\n@Example 2024-03-15T14:30:00Z",
                    "type": "string"
                },
                "experience": {
                    "description": "@Description Years of experience in training\n@Example 5",
                    "type": "integer",
                    "minimum": 0
                },
                "id": {
                    "description": "@Description Unique identifier for the profile\n@Example profile_123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "is_available": {
                    "description": "@Description Whether the trainer is currently accepting new clients\n@Example true",
                    "type": "boolean"
                },
                "rating": {
                    "description": "@Description Average rating from clients (0.00 to 5.00)\n@Example 4.75",
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0
                },
                "specialization": {
                    "description": "@Description Trainer's area of expertise\n@Example Strength Training",
                    "type": "string"
                },
                "trainer_id": {
                    "description": "@Description ID of the trainer this profile belongs to\n@Example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "updated_at": {
                    "description": "@Description When the profile was last updated\n@Example 2024-03-15T14:30:00Z",
                    "type": "string"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.UpdateCustomerRequest": {
            "description": "Request to update a customer",
            "type": "object",
            "properties": {
                "age": {
                    "description": "@Description Age of the customer\n@example 25",
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 18
                },
                "email": {
                    "description": "@Description Email address of the customer\n@example john.doe@example.com",
                    "type": "string"
                },
                "fitness_goals": {
                    "description": "@Description Fitness goals of the customer\n@example [\"Weight Loss\", \"Muscle Gain\"]",
                    "type": "string"
                },
                "full_name": {
                    "description": "@Description Full name of the customer\n@example John Doe",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "gender": {
                    "description": "@Description Gender of the customer\n@example male",
                    "enum": [
                        "male",
                        "female",
                        "other",
                        "unknown"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.Gender"
                        }
                    ]
                },
                "health_conditions": {
                    "description": "@Description Health conditions of the customer\n@example [\"Asthma\", \"Back Pain\"]",
                    "type": "string"
                },
                "height": {
                    "description": "@Description Height of the customer in centimeters\n@example 175",
                    "type": "number",
                    "maximum": 250,
                    "minimum": 100
                },
                "phone": {
                    "description": "@Description Phone number of the customer\n@example +1234567890",
                    "type": "string"
                },
                "profile_url": {
                    "description": "@Description Profile URL of the customer\n@example https://example.com/profile.jpg",
                    "type": "string"
                },
                "weight": {
                    "description": "@Description Weight of the customer in kilograms\n@example 70",
                    "type": "number",
                    "maximum": 300,
                    "minimum": 30
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.UpdateGymOwnerRequest": {
            "description": "Request to update a gym owner",
            "type": "object",
            "properties": {
                "full_name": {
                    "description": "@Description Full name of the gym owner\n@example John Doe",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "gym_name": {
                    "description": "@Description Name of the gym\n@example Fitness First",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "phone": {
                    "description": "@Description Phone number of the gym owner\n@example +1234567890",
                    "type": "string"
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.UpdateTrainerRequest": {
            "description": "Request body for updating an existing trainer",
            "type": "object",
            "properties": {
                "bio": {
                    "description": "@Description Detailed trainer biography\n@Example Certified personal trainer with expertise in strength training and rehabilitation.",
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 10
                },
                "email": {
                    "description": "@Description Email address (must be unique)\n@Example john.trainer@gymapp.com",
                    "type": "string"
                },
                "experience": {
                    "description": "@Description Years of experience\n@Example 5",
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 0
                },
                "first_name": {
                    "description": "@Description Trainer's first name\n@Example John",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "last_name": {
                    "description": "@Description Trainer's last name\n@Example Smith",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "phone": {
                    "description": "@Description Phone number (must be unique)\n@Example +1-555-123-4567",
                    "type": "string"
                },
                "specialization": {
                    "description": "@Description Area of expertise\n@Example Strength Training",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.UserType": {
            "type": "string",
            "enum": [
                "gym_owner",
                "trainer",
                "customer"
            ],
            "x-enum-varnames": [
                "UserTypeGymOwner",
                "UserTypeTrainer",
                "UserTypeCustomer"
            ]
        },
        "github_com_yourname_fitness-platform_internal_models.VerifyOTPRequest": {
            "description": "OTP verification request details",
            "type": "object",
            "required": [
                "otp",
                "user_id",
                "user_type"
            ],
            "properties": {
                "otp": {
                    "description": "@Description OTP code\n@example 123456",
                    "type": "string"
                },
                "user_id": {
                    "description": "@Description User ID\n@example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "user_type": {
                    "description": "@Description Type of user (gym_owner, trainer, customer)\n@example trainer",
                    "enum": [
                        "gym_owner",
                        "trainer",
                        "customer"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.UserType"
                        }
                    ]
                }
            }
        },
        "github_com_yourname_fitness-platform_internal_models.VerifyOTPResponse": {
            "description": "OTP verification response details",
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "@Description Access token\n@example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                    "type": "string"
                },
                "is_active": {
                    "description": "@Description Whether the user is active\n@example true",
                    "type": "boolean"
                },
                "token_type": {
                    "description": "@Description Token type\n@example Bearer",
                    "type": "string"
                },
                "user_id": {
                    "description": "@Description User ID\n@example 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "user_type": {
                    "description": "@Description User type\n@example trainer",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_yourname_fitness-platform_internal_models.UserType"
                        }
                    ]
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token for authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Operations about gym owners including registration, authentication, and profile management",
            "name": "gym-owners"
        },
        {
            "description": "Operations about trainers including profile management and availability",
            "name": "trainers"
        },
        {
            "description": "Operations about customers including registration, profile management, and fitness goals",
            "name": "customers"
        },
        {
            "description": "Operations for OTP (One-Time Password) sending and verification",
            "name": "otp"
        },
        {
            "description": "Health check endpoint for monitoring service status",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Gym Management System API",
	Description:      "A comprehensive gym management system API that handles user registration, profile management, OTP verification, and role-based access control.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
